RssItem [title=إندونيسيا.. صمت انتخابي عشية أكبر انتخابات تجرى في يوم واحد, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=يدلي عشرات الملايين من الناخبين الإندونيسيين غدا الأربعاء بأصواتهم في انتخابات رئاسية وبرلمانية الأربعاء، بعد حملات انتخابية ركزت على الاقتصاد في أكبر دولة إسلامية من حيث عدد السكان.

, link=https://www.aljazeera.net/news/politics/2019/4/16/إندونيسيا-صمت-انتخابي-أكبر-انتخابات, pubDate=Tue Apr 16 15:07:08 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/إندونيسيا-صمت-انتخابي-أكبر-انتخابات]
