RssItem [title=نازح عراقي يعيد 60 ألف دولار لعائلة فقدتها في أربيل, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أشاد عراقيون بموقف نازح من محافظة الأنبار بعدما أرجع مبلغا ماليا كبيرا مع هاتف ومصوغات ذهبية إلى عائلة فقدتها في محافظة أربيل شمالي العراق.
, link=https://www.aljazeera.net/news/miscellaneous/2019/4/16/نازح-عراقي-يعيد-دولارات-عائلة-أربيل, pubDate=Tue Apr 16 17:10:56 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=منوعات
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/miscellaneous/2019/4/16/نازح-عراقي-يعيد-دولارات-عائلة-أربيل]
