RssItem [title=بالتزامن مع التعديلات الدستورية.. "يوم عالمي" لإخلاء سبيل معتقلين بمصر, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أخلت السلطات المصرية على مدار اليومين الماضيين سبيل أعداد كبيرة من المعتقلين في قضايا سياسية، في سابقة هي الأولى من نوعها منذ الانقلاب العسكري والإطاحة بالرئيس المنتخب محمد مرسي.

, link=https://www.aljazeera.net/news/humanrights/2019/4/16/اليوم-العالمي-لإخلاء-سبيل-المعتقلين-بمصر, pubDate=Tue Apr 16 16:45:28 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=حريات
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/humanrights/2019/4/16/اليوم-العالمي-لإخلاء-سبيل-المعتقلين-بمصر]
