RssItem [title=طرابلس ترفض الحوار مع حفتر.. والأمم المتحدة تطمئنها, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=قال رئيس المجلس الأعلى للدولة الليبية إن المجلس لن يشارك بأي حوار مع خليفة حفتر بعد هجومه على طرابلس، في وقت شكك رئيس حكومة الوفاق فايز السراج بموقف الأمم المتحدة.
, link=https://www.aljazeera.net/news/politics/2019/4/16/ليبيا-خليفة-حفتر-المجلس-الأعلى-الليبي, pubDate=Tue Apr 16 21:21:43 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/ليبيا-خليفة-حفتر-المجلس-الأعلى-الليبي]
