RssItem [title=الملك غاضب.. ماذا تضمر واشنطن وحلفاؤها للأردن بصفقة القرن؟, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=ناقشت حلقة (2019/4/16) من برنامج "ما وراء الخبر" الرسائل التي تبعثها المظاهرات التي تشهدها مدن أردنية دعما لموقف المملكة من القضية الفلسطينية ودورها في الوصاية على القدس والمقدسات الإسلامية والمسيحية.
, link=https://www.aljazeera.net/programs/behindthenews/2019/4/16/الملك-غاضب-ماذا-تضمر-واشنطن-وحلفاؤها-للأردن-بصفقة-القرن, pubDate=Tue Apr 16 22:49:27 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=ما وراء الخبر
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/programs/behindthenews/2019/4/16/الملك-غاضب-ماذا-تضمر-واشنطن-وحلفاؤها-للأردن-بصفقة-القرن]
