RssItem [title=البرلمان يقر تعديلات دستورية تسمح ببقاء السيسي في السلطة حتى 2030, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=وافق البرلمان المصري اليوم خلال جلسة تصويت نهائي على جملة من التعديلات الدستورية ستتيح للرئيس الحالي عبد الفتاح السيسي إمكانية البقاء في السلطة حتى عام 2030.
, link=https://www.aljazeera.net/news/politics/2019/4/16/مصر-تعديلات-دستورية-السيسي, pubDate=Tue Apr 16 21:21:43 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/مصر-تعديلات-دستورية-السيسي]
