RssItem [title=مسيرات بالأردن دعما لموقف الملك من القدس, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=خرجت اليوم في مدن أردنية مسيرات داعمة لموقف الملك من القدس، ودوره بحماية المقدسات، وذلك في ظل حديث عن ضغوط من واشنطن ودول عربية على عمان للقبول بخطة السلام الأميركية.
, link=https://www.aljazeera.net/news/politics/2019/4/16/الأردن-مسيرات-الملك-عبد-الله-القدس-فلسطين-إسرائيل-أميركا, pubDate=Tue Apr 16 17:43:31 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/الأردن-مسيرات-الملك-عبد-الله-القدس-فلسطين-إسرائيل-أميركا]
