RssItem [title=غوغل يحتفي بإنجي أفلاطون ورحلتها من الفن للسياسة, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=احتفى محرك البحث غوغل اليوم بالذكرى 95 لميلاد إنجي أفلاطون وهي من رائدات الحركة التشكيلية المصرية، لكونها إحدى المناضلات البارزات بالحركة الاشتراكية المصرية والنسائية الحديثة.
, link=https://www.aljazeera.net/news/arts/2019/4/16/غوغل-رحلتها-إنجي-أفلاطون-الفن-السياسة, pubDate=Tue Apr 16 16:43:20 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=فن
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/arts/2019/4/16/غوغل-رحلتها-إنجي-أفلاطون-الفن-السياسة]
