RssItem [title=لوموند: ليبيا.. انتكاسة قاسية للمجتمع الدولي, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=قالت صحيفة لوموند الفرنسية إن ليبيا دخلت للتو حربها الأهلية الثالثة منذ 2011، فيما يعد فشلا مريرا أظهر بجلاء مدى العجز والانقسام الذي يعاني منه المجتمع الدولي.
, link=https://www.aljazeera.net/news/politics/2019/4/16/حفتر-ليبيا-صراع-السراج-طرابلس-تنظيم-الدولة-المجتمع-الدولي, pubDate=Tue Apr 16 18:24:45 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/حفتر-ليبيا-صراع-السراج-طرابلس-تنظيم-الدولة-المجتمع-الدولي]
