RssItem [title=قطر: حفتر يعرقل جهود الحوار بليبيا.. والحل بفرض حظر السلاح, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=بحث رئيس الوزراء الإيطالي مع وزير الخارجية القطري في روما تطورات الأزمة الليبية، واعتبر الوزير القطري أن تحركات اللواء المتقاعد خليفة حفتر تعرقل الحل السياسي، وطالب بفرض حظر السلاح.
, link=https://www.aljazeera.net/news/politics/2019/4/16/إيطاليا-جوزيبي-كونتي-قطر-محمد-بن-عبد-الرحمن-آل-ثاني-روما-ليبيا-خليفة-حفتر, pubDate=Tue Apr 16 14:15:42 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/إيطاليا-جوزيبي-كونتي-قطر-محمد-بن-عبد-الرحمن-آل-ثاني-روما-ليبيا-خليفة-حفتر]
