RssItem [title=ليبيا.. طيران الوفاق يقصف قاعدة لحفتر وأعداد الضحايا والنازحين بارتفاع, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=وجهت قوات حكومة الوفاق الوطني ضربة جوية لقاعدة عسكرية لقوات خليفة حفتر وسط ليبيا، وأكدت تقدمها في أحد محاور القتال جنوب طرابلس، في حين رفعت المعارك حصيلة النازحين من المدنيين.
, link=https://www.aljazeera.net/news/politics/2019/4/16/حكومة-الوفاق-الوطني-الليبية-غارة-جوية-الجفرة-قوات-حفتر, pubDate=Tue Apr 16 16:27:00 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/حكومة-الوفاق-الوطني-الليبية-غارة-جوية-الجفرة-قوات-حفتر]
