RssItem [title=بتهم "الإرهاب".. أحكام بسجن العشرات وإسقاط الجنسية في البحرين, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أدانت محكمة بحرينية الثلاثاء 169 متهما بالانضمام لجماعة إرهابية، وأصدرت بحقهم أحكاما متفاوتة بالسجن، وإسقاط الجنسية عن 138، في القضية المعروفة إعلاميا باسم حزب الله البحريني.
, link=https://www.aljazeera.net/news/politics/2019/4/16/البحرين-محكمة-إرهاب-سجن-إسقاط-جنسية, pubDate=Tue Apr 16 18:24:45 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/البحرين-محكمة-إرهاب-سجن-إسقاط-جنسية]
