RssItem [title=حماية لهم.. بريطانيا تمنع أطفالها من إرسال الإعجاب على فيسبوك وسناب شات, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=بعد انتقاد الأمير هاري لها واتهامها بالتسبب بإدمان الأطفال، طلبت مفوضة المعلومات من شبكات التواصل عدم السماح لمستخدميها دون سن 18 سنة بإرسال علامات الإعجاب على المواقع. 
, link=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/حماية-لهم-بريطانيا-تمنع-أطفالها-من-إرسال-الإعجاب-على-فيسبوك-وسناب-شات, pubDate=Tue Apr 16 19:19:39 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=أخبار وقضايا
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/حماية-لهم-بريطانيا-تمنع-أطفالها-من-إرسال-الإعجاب-على-فيسبوك-وسناب-شات]
