RssItem [title=تضم قصور صدام.. هذا موعد الافتتاح الكامل للمنطقة الخضراء ببغداد , description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=تتجه الحكومة العراقية إلى إعادة فتح المنطقة الخضراء شديدة التحصين وسط العاصمة بغداد بشكل كامل أمام المواطنين بعد سنوات من الإغلاق، وتعرف المنطقة بفخامتها وقصورها وكثرة نخليها.

, link=https://www.aljazeera.net/news/miscellaneous/2019/4/16/المنطقة-الخضراء-بغداد-موعد-افتتاح, pubDate=Tue Apr 16 15:16:59 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=منوعات
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/miscellaneous/2019/4/16/المنطقة-الخضراء-بغداد-موعد-افتتاح]
