RssItem [title=أطفال "النطف المهربة" محرومون من زيارة آبائهم في سجون الاحتلال, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value="سفراء الحرية" تسمية يطلقها الفلسطينيون على أبناء الأسرى الذين أنجبوا عن طريق تهريب نطف آبائهم، حيث تكررت تلك الحالات منذ عام 1998 وعن طريقها أنجب 51 أسيرا 69  طفلا.
, link=https://www.aljazeera.net/news/politics/2019/4/16/فلسطين-الأسرى-النطف-المهربة-السجون-الإسرائيلية-غزة-حماس-إسرائيل, pubDate=Tue Apr 16 14:46:34 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/فلسطين-الأسرى-النطف-المهربة-السجون-الإسرائيلية-غزة-حماس-إسرائيل]
