RssItem [title=الدفاع المدني الفرنسي لترامب: نصائحك كفيلة بهدم الكاتدرائية بكاملها, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=رصدت نشرة الثامنة "نشرتكم" بتاريخ (2019/4/16) تفاعل الفرنسيين الغاضب والساخر من تغريدة نشرها الرئيس الأميركي دونالد ترامب قدم فيها نصائح لإخماد سريع لحريق كاتدرائية نوتردام.

, link=https://www.aljazeera.net/programs/aja-interactive/2019/4/16/الدفاع-المدني-الفرنسي-لترامب-نصائحك-كفيلة-بهدم-الكاتدرائية-بكاملها, pubDate=Tue Apr 16 21:12:37 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=نشرة الثامنة – نشرتكم
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/programs/aja-interactive/2019/4/16/الدفاع-المدني-الفرنسي-لترامب-نصائحك-كفيلة-بهدم-الكاتدرائية-بكاملها]
