RssItem [title=بالفيديو.. هكذا أغرقت السيول قرى عراقية, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=غرقت عدة قرى بأكملها ونزح آلاف المواطنين جراء السيول التي ضربت محافظة ميسان جنوب العراق على مدار الأسبوعين الماضيين.
, link=https://www.aljazeera.net/news/politics/2019/4/16/هكذا-أغرقت-السيول-قرى-عراقية, pubDate=Tue Apr 16 19:40:50 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/هكذا-أغرقت-السيول-قرى-عراقية]
