RssItem [title=وقف تحويل العلاج بإسرائيل.. موقف ضد الاحتلال أم عقاب لغزة؟, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=ألقى قرار السلطة الفلسطينية، وقف التحويلات الطبية إلى مستشفيات إسرائيلية، بظلال قاتمة على المرضى في غزة خصوصا من لا يجدون علاجا لحالاتهم بمستشفيات القطاع.
, link=https://www.aljazeera.net/news/politics/2019/4/16/فلسطين-غزة-مرضى-السلطة-الفلسطينية-المستشفيات-الإسرائيلية, pubDate=Tue Apr 16 14:46:34 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/فلسطين-غزة-مرضى-السلطة-الفلسطينية-المستشفيات-الإسرائيلية]
