RssItem [title=بالبيض والتونة.. الحكومة تعلن الحرب على الثعابين السامة بدلتا مصر, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=حالة من الخوف والترقب بين أهالي محافظة المنوفية عقب وفاة أسامة -أحد المزارعين بإحدى قرى مركز قويسنا التابع للمحافظة- مؤخرًا، حيث تعرض للدغة ثعبان سام أثناء عمله اليومي في الحقل.
, link=https://www.aljazeera.net/news/miscellaneous/2019/4/16/الحرب-الثعابين-السامة-دلتا-مصر, pubDate=Tue Apr 16 09:23:07 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=منوعات
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/miscellaneous/2019/4/16/الحرب-الثعابين-السامة-دلتا-مصر]
