RssItem [title=النيل يجري شمالا.. هل أربكت ثورة السودان السيسي وغيرت مسار تعديلات الدستور؟, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أرجع مراقبون إعادة صياغة تعديلات دستورية تمدد بقاء السيسي بالسلطة، إلى الحراك السوداني الجزائري الذي أطاح برئيسي البلدين، بينما اعتقد آخرون أن رفض واشنطن ربما يكون السبب الأكثر تأثيرا.
, link=https://www.aljazeera.net/news/politics/2019/4/16/هل-تقلصت-تعديلات-الدستور-بمصر-خوفا-من-عدوى-الثورة, pubDate=Tue Apr 16 14:46:34 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/هل-تقلصت-تعديلات-الدستور-بمصر-خوفا-من-عدوى-الثورة]
