RssItem [title="أنا أُنفذ الأوامر".. كيف يتحول الناس إلى أشرار؟, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=في محيطنا العربي نرى أصنافًا من القسوة التي لا تنتهي، فلماذا يفعل الإنسان كل هذا؟ هل نحن أشرار بالفطرة؟ أم أن للبيئة والملابسات والسلطة أثر في كل ذلك؟
, link=https://midan.aljazeera.net/intellect/sociology/2019/4/16/أنا-أنفذ-الأوامر-كيف-يتحول-الناس-إلى-أشرار, pubDate=Tue Apr 16 13:56:17 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=اجتماع
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://midan.aljazeera.net/intellect/sociology/2019/4/16/أنا-أنفذ-الأوامر-كيف-يتحول-الناس-إلى-أشرار]
