RssItem [title=محمود السيسي.. نجل الرئيس وقائد كتيبة تعديل الدستور, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=تعاظمت الشواهد على الدور الذي يقوم به محمود السيسي نجل الرئيس المصري عبد الفتاح السيسي في إدارة عمليات وراء الكواليس لتثبيت حكم والده وضمان استدامته إلى أبعد الآجال.
, link=https://www.aljazeera.net/news/politics/2019/4/16/مصر-السيسي-العميد-محمود-الدستور, pubDate=Tue Apr 16 23:12:45 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/مصر-السيسي-العميد-محمود-الدستور]
