RssItem [title=أميركا تلمح لإزالة السودان من لائحة الإرهاب.. وأوغندا مستعدة لاستقبال البشير, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=صرح مسؤول كبير بالخارجية الأميركية بأن واشنطن ستبحث رفع اسم السودان من قائمة الإرهاب إذا رأت تغييرات جوهرية بحكومته وانتقالا سياسيا سلسا، بينما ألمحت أوغندا لإمكانية منح عمر البشير اللجوء.


, link=https://www.aljazeera.net/news/politics/2019/4/16/السودان-أميركا-عقوبات-الإرهاب-أوغندا-عمر-البشير-اللجوء-المجلس-العسكري, pubDate=Tue Apr 16 23:12:45 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/السودان-أميركا-عقوبات-الإرهاب-أوغندا-عمر-البشير-اللجوء-المجلس-العسكري]
