RssItem [title=كاتدرائية نوتردام.. هذا ما عانته عبر التاريخ قبل الحريق, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=في قلب باريس وخلال الأسبوع المقدس لدى ملايين المسيحيين الذين يحيون "أسبوع الآلام" وبينما كانت كاتدرائية نوتردام تستعد لاستقبال زوارها، اجتاحت النار البناية التاريخية التي تعود لما يقرب ثمانية قرون.
, link=https://www.aljazeera.net/news/cultureandart/2019/4/16/نوتردام-كاتدرائية-كاثوليكية-الأحداث-تحرقها-النيران-أسبوع-الآلام, pubDate=Tue Apr 16 15:38:34 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=ثقافة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/cultureandart/2019/4/16/نوتردام-كاتدرائية-كاثوليكية-الأحداث-تحرقها-النيران-أسبوع-الآلام]
