RssItem [title=يوتيوب يربط بين حريق كاتدرائية نوتردام وهجمات 11 سبتمبر, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=وجدت خوارزمية يوتيوب رابطا غريبا بين حريق كاتدرائية نوتردام وهجمات 11 سبتمبر، هذا ما تقوله الفيديوهات التي نشرت في الولايات المتحدة أثناء بث يوتيوب مشاهد الحريق وتحته فيديوهات لهجمات سبتمبر.
, link=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/يوتيوب-يربط-بين-حريق-كاتدرائية-نوتردام-وهجمات-سبتمبر, pubDate=Tue Apr 16 13:23:15 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=أخبار وقضايا
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/يوتيوب-يربط-بين-حريق-كاتدرائية-نوتردام-وهجمات-سبتمبر]
