RssItem [title=إحباط اقتصادي يجتاح دبي والأزمة تمتد للسياحة والتعليم, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=قال وكالة بلومبيرغ إن اقتصاد دبي البالغ 108 مليارات دولار ما زال يكافح من أجل النمو، لكن حالة الضيق والإحباط بدأت تتجاوز قطاع العقارات لمجالات أخرى رغم تحسن أسعار النفط.
, link=https://www.aljazeera.net/news/ebusiness/2019/4/16/إحباط-اقتصادي-يجتاح-إمارة-دبي-وهذه-هي-المؤشرات, pubDate=Tue Apr 16 12:50:26 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=الاقتصاد
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/ebusiness/2019/4/16/إحباط-اقتصادي-يجتاح-إمارة-دبي-وهذه-هي-المؤشرات]
