RssItem [title=بحجم حبة الكرز.. أول قلب بتقنية الطباعة ثلاثية الأبعاد, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=تتطور التكنولوجيا وتدفع العلم للتطور في مجالات مختلفة، وها هي تقنية الطباعة ثلاثية الأبعاد تساعد العلماء في تطوير أول قلب مطبوع بهذه التقنية من أنسجة بشرية، لكن هل يعمل؟
, link=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/تطوير-أول-قلب-باستخدام-تقنية-الطباعة-ثلاثية-الأبعاد, pubDate=Tue Apr 16 16:38:22 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=أخبار وقضايا
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/scienceandtechnology/2019/4/16/تطوير-أول-قلب-باستخدام-تقنية-الطباعة-ثلاثية-الأبعاد]
