RssItem [title=واشنطن بوست: الأمير السعودي المتهور يؤجج حربا أهلية أخرى, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=كتبت صحيفة واشنطن بوست الأميركية في افتتاحيتها اليوم أن "الأمير السعودي المتهور يشعل حربا أهلية أخرى"، وقالت الصحيفة إن الهجوم العسكري على طرابلس شن بدعم مالي من السعودية والإمارات ومصر.


, link=https://www.aljazeera.net/news/politics/2019/4/16/واشنطن-بوست-الأمير-السعودي-بن-سلمان-يؤجج-حربا-أهلية-أخرى-ليبيا, pubDate=Tue Apr 16 09:58:57 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/واشنطن-بوست-الأمير-السعودي-بن-سلمان-يؤجج-حربا-أهلية-أخرى-ليبيا]
