RssItem [title=سكرتيرة تغلبت على رئيسها لتصبح عمدة مقاطعة بتركيا, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=استقالت زكية تيكين من منصب كاتبة العمدة الصيف الماضي، بعد تنزيل رئيسها السابق ومنافسها بالانتخابات، مظفر يالجين، رتبتها الوظيفية دون تفسير، وخاضت الانتخابات البلدية بمقاطعة "بيلاجيك" مرشحةً مستقلةً، لتفوز عليه.
, link=https://www.aljazeera.net/news/women/2019/4/16/السكرتيرة-التي-تغلبت-على-رئيسها-لتصبح-عمدة-مقاطعة-بيلاجيك-تركيا, pubDate=Tue Apr 16 14:15:12 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=مرأة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/women/2019/4/16/السكرتيرة-التي-تغلبت-على-رئيسها-لتصبح-عمدة-مقاطعة-بيلاجيك-تركيا]
