RssItem [title=علماء يتوصلون "للصندوق الأسود" لأصل مرض السرطان, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=توصلت دراسة طبية حديثة إلى أن سبب السرطان مكتوب في الحمض النووي، مما قد يشكل "الصندوق الأسود" لأصل مرض السرطان.
, link=https://www.aljazeera.net/news/healthmedicine/2019/4/16/علماء-يتوصلون-للصندوق-الأسود-لأصل-مرض-السرطان, pubDate=Tue Apr 16 23:04:11 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=اخترنا لك
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/healthmedicine/2019/4/16/علماء-يتوصلون-للصندوق-الأسود-لأصل-مرض-السرطان]
