RssItem [title=كاتدرائية نوتردام.. النيران تلتهم أجمل رموز باريس , description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=
, link=https://www.aljazeera.net/Home/GetPage/99338cb4-e24c-4e32-8e71-ec101ba17a23/b07fed0b-4263-4b10-a58c-f6fc1f7b1856, pubDate=Tue Apr 16 12:15:20 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=بالصور
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/Home/GetPage/99338cb4-e24c-4e32-8e71-ec101ba17a23/b07fed0b-4263-4b10-a58c-f6fc1f7b1856]
