RssItem [title=قائد الجيش الجزائري: الوقت يداهمنا ورئيس المخابرات السابق تآمر على الشعب, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=طالب الفريق أحمد قايد صالح قائد أركان الجيش الجزائري ونائب وزير الدفاع بحل عاجل لأزمة الجزائر، وهاجم بشكل مباشر القائد السابق لجهاز المخابرات محمد مدين المدعو توفيق.
, link=https://www.aljazeera.net/news/politics/2019/4/16/قايد-صالح-الجزائر-بوتفليقة-الجنرال-توفيق-حراك-الجزائر, pubDate=Tue Apr 16 17:43:31 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/قايد-صالح-الجزائر-بوتفليقة-الجنرال-توفيق-حراك-الجزائر]
