RssItem [title=الشوكولاتة تحافظ على سمعك, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=خلصت دراسة علمية إلى أن الشوكولاتة يمكنها أن تساعد في الحماية من فقدان السمع.
, link=https://www.aljazeera.net/news/healthmedicine/2019/4/16/الشوكولاتة-للحفاظ-على-السمع, pubDate=Tue Apr 16 17:10:27 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=أحدث الدراسات
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/healthmedicine/2019/4/16/الشوكولاتة-للحفاظ-على-السمع]
