RssItem [title=بعد إعلان المجلس العسكري السوداني.. قلق من دور إماراتي سعودي, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=عززت تطمينات المجلس العسكري الذي يدير مقاليد الأمور في السودان بالإبقاء على القوات السودانية في حرب اليمن، مخاوف بدأت تزداد يوما بعد يوم بشأن دور سعودي إماراتي.
, link=https://www.aljazeera.net/news/politics/2019/4/16/القوات-السودانية-اليمن-الإمارات-السعودية, pubDate=Tue Apr 16 22:12:37 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/القوات-السودانية-اليمن-الإمارات-السعودية]
