RssItem [title=بدعم الأحزاب اليمينية... نتنياهو يتأهل لولاية خامسة, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=حاز رئيس الوزراء الإسرائيلي بنيامين نتنياهو على أغلبية من 65 عضوا في الكنيست (البرلمان) أوصوا الرئيس الإسرائيلي رؤبين ريفلين بتكليفه لتشكيل حكومة جديدة في إسرائيل.
, link=https://www.aljazeera.net/news/politics/2019/4/16/بنيامين-نتنياهو-الكنيست-إسرائيل-انتخابات, pubDate=Tue Apr 16 17:02:40 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/بنيامين-نتنياهو-الكنيست-إسرائيل-انتخابات]
