RssItem [title=فرنسا وحراك الجزائر.. لاعب رئيسي أم فزاعة لمآرب أخرى؟, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=خطاب قائد أركان الجيش الجزائري الفريق قايد صالح فتح نقاشا واسعا بشأن دور فرنسا واحتمال تدخلها في الحراك. فهل تسعى باريس لتوجيه الأحداث بما يخدم مصالحها؟
, link=https://www.aljazeera.net/news/politics/2019/4/16/الجزائر-فرنسا-قايد-صالح-بوتفليقة-حراك-الجزائر, pubDate=Tue Apr 16 14:46:34 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/الجزائر-فرنسا-قايد-صالح-بوتفليقة-حراك-الجزائر]
