RssItem [title=شملت منظومة أس-400.. وزيران تركيان أجريا مباحثات "بناءة" بواشنطن, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=قال وزير المالية التركي إن الرئيس الأميركي دونالد ترامب تفهم حاجة بلاده لشراء منظومة أس-400 الروسية الدفاعية، في وقت ذكر وزير الدفاع أن هذه الصفقة يجب ألا تؤدي لعقوبات أميركية.


, link=https://www.aljazeera.net/news/politics/2019/4/16/براءت-ألبيرق-دونالد-ترامب-تركيا-روسيا-خلوصي-أكار, pubDate=Tue Apr 16 13:23:38 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/براءت-ألبيرق-دونالد-ترامب-تركيا-روسيا-خلوصي-أكار]
