RssItem [title=بعد دوري الأبطال.. الحاسوب الخارق يتوقع الفائز بلقب بريميرليغ, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=على بعد أربع مراحل من إسدال الستار على هذا الموسم من الدوري الإنجليزي الممتاز لكرة القدم، ومع ارتفاع وتيرة المنافسة بين ليفربول ومانشستر سيتي، دخل حاسوب خارق على الخط ليتوقع هوية حامل اللقب.
, link=https://sport.aljazeera.net/football/premierleague/2019/4/16/دوري-الأبطال-بريميرليغ-مان-سيتي-ليفربول-توتنهام-تشلسي, pubDate=Tue Apr 16 16:57:42 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=الدوري الإنجليزي الممتاز
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://sport.aljazeera.net/football/premierleague/2019/4/16/دوري-الأبطال-بريميرليغ-مان-سيتي-ليفربول-توتنهام-تشلسي]
