RssItem [title=السودان.. إقالات وتعيينات جديدة للمجلس العسكري, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أقال المجلس العسكري الانتقالي بالسودان النائب العام ونائبه، وعين رئيسا جديدا للجهاز القضائي عقب إقالة رئيسه الحالي، وشملت التغييرات إعفاء مدير الهيئة القومية للإذاعة والتلفزيون.
, link=https://www.aljazeera.net/news/politics/2019/4/16/السودان-المجلس-العسكري-الانتقالي-قرارات-إعفاء-تعيين-القضاء-الإعلام, pubDate=Tue Apr 16 21:21:43 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/السودان-المجلس-العسكري-الانتقالي-قرارات-إعفاء-تعيين-القضاء-الإعلام]
