RssItem [title=السعودية.. سوق العمل تطرد 1.6 مليون وافد في عامين, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=أفاد تقرير مختص بأن إجمالي عدد الوافدين الذين غادروا سوق العمل السعودي خلال العامين الماضيين بلغ 1.6 مليون عامل، بسبب مضاعفة رسوم العمالة الأجنبية للأفراد وعائلاتهم.
, link=https://www.aljazeera.net/news/ebusiness/2019/4/16/سوق-العمل-السعودية-تطرد-أكثر-من-مليون-وافد-في-عامين, pubDate=Tue Apr 16 19:25:47 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=الاقتصاد
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/ebusiness/2019/4/16/سوق-العمل-السعودية-تطرد-أكثر-من-مليون-وافد-في-عامين]
