RssItem [title=أبطال صغار.. أنقذوا أرواح من حولهم بشجاعة, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=يحدث أن نصِف أفعالا صغيرة ينجزها الطفل بـ "البطولة" لدعمه وتشجيعه وحثه على إنجاز الأكبر، فكيف إذا أنقذ طفل حياة الآخرين؟ هل يفيهم حقهم أن نصفهم بالأبطال.
, link=https://www.aljazeera.net/news/women/2019/4/16/أبطال-صغار-أطفال-أنقذوا-أرواح-من-حولهم-بشجاعة, pubDate=Tue Apr 16 20:52:04 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=مرأة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/women/2019/4/16/أبطال-صغار-أطفال-أنقذوا-أرواح-من-حولهم-بشجاعة]
