RssItem [title=الخصخصة تثير غضب أطباء وطلبة الطب في المغرب, description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=تقصد أميمة أوعتاني يوميا كلية الطب بالرباط، ليس للدراسة ولكن للمشاركة في الاحتجاجات والاعتصامات التي يقوم بها طلبة الكلية وباقي كليات الطب والصيدلة بالمغرب، منذ فبراير/شباط الماضي.


, link=https://www.aljazeera.net/news/politics/2019/4/16/المغرب-خصخصة-طلبة-الطب-احتجاجات, pubDate=Tue Apr 16 23:03:00 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/المغرب-خصخصة-طلبة-الطب-احتجاجات]
