RssItem [title=حريق نوتردام.. ترجيح فرضية الحادث وتبرعات لإعادة بناء الكاتدرائية  , description=SyndContentImpl.mode=null
SyndContentImpl.type=text/html
SyndContentImpl.interface=interface com.rometools.rome.feed.synd.SyndContent
SyndContentImpl.value=قال المدعي العام في باريس ريمي هايتس اليوم الثلاثاء إنه لا يوجد أي دليل على جريمة الحريق العمد في حادثة كاتدرائية نوتردام التاريخية.
, link=https://www.aljazeera.net/news/politics/2019/4/16/باريس-كاتدرائية-نوتردام-فرنسا-حريق, pubDate=Tue Apr 16 18:24:45 EEST 2019, categories=[SyndCategoryImpl.taxonomyUri=null
SyndCategoryImpl.name=سياسة
SyndCategoryImpl.interface=interface com.rometools.rome.feed.synd.SyndCategory
], comments=https://www.aljazeera.net/news/politics/2019/4/16/باريس-كاتدرائية-نوتردام-فرنسا-حريق]
